version: '3.8'

services:
    db:
        image: ankane/pgvector
        container_name: pgvector-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: vibe-match-db
        ports:
            - "5433:5432"
